// action type for authentication
export const LOGIN_ATTEMPTED = 'LOGIN_ATTEMPTED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'

// action type for leave request
export const REQUEST_LEAVES = 'REQUEST_LEAVES'
export const REQUEST_LEAVES_SUCCESS = 'REQUEST_LEAVES_SUCCESS'
export const REQUEST_LEAVES_FAILED = 'REQUEST_LEAVES_FAILED'
export const RECEIVE_LEAVES = 'RECEIVE_LEAVES'
export const ADD_REQUEST = 'ADD_REQUEST'
export const SELECT_REQUEST = 'SELECT_REQUEST'
export const CLEAR_REQUESTS_LIST = 'CLEAR_REQUESTS_LIST'
export const UPDATE_REQUEST = 'UPDATE_REQUEST'
export const UPDATE_REQUEST_SUCCESS = 'UPDATE_REQUEST_SUCCESS'
export const UPDATE_REQUEST_FAILED = 'UPDATE_REQUEST_FAILED'
export const UPDATE_REQUEST_MULTIPLE = 'UPDATE_REQUEST_MULTIPLE'
export const UPDATE_MULTIPLE_SUCCESS = 'UPDATE_MULTIPLE_SUCCESS'
export const UPDATE_MULTIPLE_FAILED = 'UPDATE_MULTIPLE_FAILED'
export const DELETE_LEAVE = 'DELETE_LEAVE'
export const SEARCH_LEAVE = 'SEARCH_LEAVE'

// users request
export const REQUEST_USER = 'REQUEST_USER'
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS'
export const REQUEST_USER_FAILED = 'REQUEST_USER_FAILED'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'
export const ADD_USER = 'ADD_USER'
export const SELECT_USER = 'SELECT_USER' // nanti data disini sekaligus trigger buat nampilin detail modal
export const EDIT_USER = 'EDIT_USER' // nanti data disini sekaligus trigger buat nampilin edit modal
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const CHANGE_PASSWORD_USER = 'CHANGE_PASSWORD_USER'

// company request both for super admin and admin
// this is for admin
export const GET_GOOGLE_URL = 'GET_GOOGLE_URL'
export const SELECT_SINGLE_COMPANY = 'SELECT_SINGLE_COMPANY'
export const UPDATE_SINGLE_COMPANY = 'UPDATE_SINGLE_COMPANY'
export const DELETE_COMPANY = 'DELETE_COMPANY'
export const GET_GOOGLE_CALENDAR = 'GET_GOOGLE_CALENDAR'
export const VERIFY_GOOGLE_CALENDAR = 'VERIFY_GOOGLE_CALENDAR'
export const UPDATE_GOOGLE_CALENDAR = 'UPDATE_GOOGLE_CALENDAR'
export const NO_GOOGLE_CALENDAR = 'NO_GOOGLE_CALENDAR'
export const REQUEST_EXCLUDED_DATE = 'REQUEST_EXCLUDED_DATE'
export const REQUEST_EXCLUDED_DATE_SUCCESS = 'REQUEST_EXCLUDED_DATE_SUCCESS'
export const REQUEST_EXCLUDED_DATE_FAILED = 'REQUEST_EXCLUDED_DATE_FAILED'
export const ADD_EXCLUDED_DATE = 'ADD_EXCLUDED_DATE'
export const GET_ANALYTICS_SUCCESS = 'GET_ANALYTICS_SUCCESS'

// this is for superadmin
export const ADD_COMPANY = 'ADD_COMPANY'
export const REQUEST_COMPANY = 'REQUEST_COMPANY'
export const REQUEST_COMPANY_SUCCES = 'REQUEST_COMPANY_SUCCES'
export const REQUEST_COMPANY_FAILED = 'REQUEST_COMPANY_FAILED'
export const SELECT_COMPANY = 'SELECT_COMPANY'
export const UPDATE_COMPANY = 'UPDATE_COMPANY'


// admin requests
export const REQUEST_ADMIN = 'REQUEST_ADMIN'
export const REQUEST_ADMIN_SUCCESS = 'REQUEST_ADMIN_SUCCESS'
export const REQUEST_ADMIN_FAILED = 'REQUEST_ADMIN_FAILED'
export const SELECT_ADMIN = 'SELECT_ADMIN'
export const SELECT_ADMIN_API = 'SELECT_ADMIN_API'
export const ADD_ADMIN = 'ADD_ADMIN'
export const UPDATE_ADMIN = 'UPDATE_ADMIN'
export const CHANGE_PASSWORD_ADMIN = 'CHANGE_PASSWORD_ADMIN'
export const DELETE_ADMIN = 'DELETE_ADMIN'